Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>A custom object to store job applications</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Contact that represents the main point of contact for the job such as a recruiter or an employee at the company</description>
    <inlineHelpText>For example, recruiter or employee at the company</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application_Contact__c/Job_Application_Contact__c.object-meta.xml
<CustomObject>
    <description>A custom object to store job application contacts</description>
    <label>Job Application Contact</label>
    <nameField>
        <displayFormat>Contact-{0000}</displayFormat>
        <label>Job Application Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Application Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Contact that represents a pivotal individual associated with the company such as a recruiter or an employee</description>
    <inlineHelpText>For example, recruiter or employee at the company</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Application Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a Job Application associated with this contact</description>
    <inlineHelpText>Select the job application associated with this contact</inlineHelpText>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Application Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/classes/JobApplicationContactTriggerHandler.cls
public with sharing class JobApplicationContactTriggerHandler {
    public void setPrimaryContact(List<Job_Application_Contact__c> triggerDotNew) {
        Map<Id, Id> contactIdsByJobApplicationId = new Map<Id, Id>();

        for (Job_Application_Contact__c newJobApplicationContact : triggerDotNew) {
            if (!contactIdsByJobApplicationId.containsKey(newJobApplicationContact.Job_Application__c)) {
                contactIdsByJobApplicationId.put(newJobApplicationContact.Job_Application__c, newJobApplicationContact.Contact__c);
            }
        }

        List<Job_Application__c> jobApplicationsToUpdate = [
            SELECT 
                Id, 
                Primary_Contact__c 
            FROM Job_Application__c 
            WHERE Id IN :contactIdsByJobApplicationId.keySet() 
                AND Primary_Contact__c = null 
            WITH USER_MODE
        ];

        if (!jobApplicationsToUpdate.isEmpty()) {
            for (Job_Application__c jobApplicationToUpdate : jobApplicationsToUpdate) {
                if (contactIdsByJobApplicationId.containsKey(jobApplicationToUpdate.Id)) {
                    jobApplicationToUpdate.Primary_Contact__c = contactIdsByJobApplicationId.get(jobApplicationToUpdate.Id);
                }
            }

            if (Schema.sObjectType.Job_Application__c.isUpdateable()) {
                update as user jobApplicationsToUpdate;
            }
        }
    }
}