Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>A custom object to store job applications</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <description>A date field to specify when to follow up on the application</description>
    <inlineHelpText>Follow up on the application by this date</inlineHelpText>
    <label>Follow-Up Date</label>
    <type>Date</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>A text field that can hold a lot of information for note-taking</description>
    <inlineHelpText>Take notes here</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This picklist field will track the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/classes/JobApplicationCleaningQueueable.cls
public with sharing class JobApplicationCleaningQueueable implements Queueable {
    public void execute(QueueableContext context) {
        final List<String> STATUSES = new List<String>{'Closed', 'Accepted'};

        List<Job_Application__c> staleJobApplications = [
            SELECT 
                Status__c, 
                Follow_Up_Date__c, 
                Notes__c 
            FROM Job_Application__c 
            WHERE Status__c NOT IN :STATUSES 
                AND Follow_Up_Date__c != null 
                AND Follow_Up_Date__c <= N_DAYS_AGO:30 
            WITH USER_MODE
        ];

        for (Job_Application__c staleJobApplication : staleJobApplications) {
            staleJobApplication.Status__c = 'Closed';

            final String NOTE = '\n\n Update: Stale job application was closed by an automated process on ' + Datetime.now().format();

            if (String.isBlank(staleJobApplication.Notes__c)) {
                staleJobApplication.Notes__c = NOTE.trim();
            } else {
                staleJobApplication.Notes__c += NOTE;
            }
        }

        if (Schema.sObjectType.Job_Application__c.isUpdateable()) {
            update as user staleJobApplications;
        }
    }
}