Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>A custom object to store job applications</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Federal_Income_Tax__c.field-meta.xml
<CustomField>
    <fullName>Federal_Income_Tax__c</fullName>
    <description>Estimate of federal income tax</description>
    <label>Federal Income Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Medicare_Withholding__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Withholding__c</fullName>
    <description>Estimate of Medicare withholding</description>
    <label>Medicare Withholding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>A numerical field to capture the expected salary for the job position</description>
    <inlineHelpText>Expected salary for the job position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Social_Security_Tax__c.field-meta.xml
<CustomField>
    <fullName>Social_Security_Tax__c</fullName>
    <description>Estimate of Social Security tax (6.20% as of 2023)</description>
    <label>Social Security Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/classes/TaxCalculation.cls
public with sharing class TaxCalculation {
    @AuraEnabled(cacheable=true)
    public static Decimal calculateFederalTax(Decimal salary) {
        Decimal federalTax = 0;

        Decimal salaryMinusStandardDeduction = salary - 13850;

        if (salaryMinusStandardDeduction == null || salaryMinusStandardDeduction <= 0) {
            return federalTax;
        } else if (salaryMinusStandardDeduction <= 11000) {
            federalTax = (salaryMinusStandardDeduction * 0.10);
        } else if (salaryMinusStandardDeduction <= 44725) {
            federalTax = ((salaryMinusStandardDeduction - 11000) * 0.12 + 1100);
        } else if (salaryMinusStandardDeduction <= 95375) {
            federalTax = ((salaryMinusStandardDeduction - 44725) * 0.22 + 5147);
        } else if (salaryMinusStandardDeduction <= 182100) {
            federalTax = ((salaryMinusStandardDeduction - 95375) * 0.24 + 16290);
        } else if (salaryMinusStandardDeduction <= 231250) {
            federalTax = ((salaryMinusStandardDeduction - 182100) * 0.32 + 37104);
        } else if (salaryMinusStandardDeduction <= 578125) {
            federalTax = ((salaryMinusStandardDeduction - 231250) * 0.35 + 52832);
        } else if (salaryMinusStandardDeduction > 578125) {
            federalTax = ((salaryMinusStandardDeduction - 578125) * 0.37 + 174238.25);
        }

        return federalTax.setScale(2, System.RoundingMode.HALF_UP);
    }

    @AuraEnabled(cacheable=true)
    public static Decimal calculateSocialSecurityTax(Decimal salary) {
        Decimal socialSecurityTax = 0.00;
        if (salary > 0){
            socialSecurityTax = (salary * 0.062);
            socialSecurityTax.setScale(2, System.RoundingMode.HALF_UP);
        }
        return socialSecurityTax;
    }

    @AuraEnabled(cacheable=true)
    public static Decimal calculateMedicareTax(Decimal salary) {
        Decimal medicareTaxes = 0.00;
        if (salary > 0){
            medicareTaxes = (salary * 0.0145);
            medicareTaxes.setScale(2, System.RoundingMode.HALF_UP);
        }
        return medicareTaxes;
    }

    public static void calculatePayrollTaxes(List<Job_Application__c> triggerDotNew) {
        for (Job_Application__c newJobApplication : triggerDotNew) {
            if (newJobApplication.Salary__c != null) {
                newJobApplication.Federal_Income_Tax__c = TaxCalculation.calculateFederalTax(newJobApplication.Salary__c);
                newJobApplication.Social_Security_Tax__c = TaxCalculation.calculateSocialSecurityTax(newJobApplication.Salary__c);
                newJobApplication.Medicare_Withholding__c = TaxCalculation.calculateMedicareTax(newJobApplication.Salary__c);
            }
        }
    }
}