Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>A custom object to store jobs</description>
    <label>Job</label>
    <nameField>
        <displayFormat>Job-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>A text field to store the job company</description>
    <label>Company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>A text field to store the job Id</description>
    <externalId>true</externalId>
    <label>Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>A text field to store the job location</description>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>A text field to store the job salary</description>
    <label>Salary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>A URL field to store the job source</description>
    <label>Source</label>
    <type>Url</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>A text field to store the job title</description>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>A text field to store the job type</description>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/classes/JoobleJSONCalloutTest.cls
@IsTest
private with sharing class JoobleJSONCalloutTest {
    private static JoobleJSONCalloutMockGenerator joobleJSONCalloutMockGenerator = new JoobleJSONCalloutMockGenerator();

    @IsTest
    private static void make_POST_callout_creates_three_jobs() {
        // GIVEN
        joobleJSONCalloutMockGenerator.statusCode = 200;

        Test.setMock(HttpCalloutMock.class, joobleJSONCalloutMockGenerator);

        // WHEN
        Test.startTest();

        JoobleJSONCallout.makePOSTCallout(
            'Junior Salesforce Developer', 
            'Remote', 
            '25', 
            50000, 
            '2024-04-15', 
            '1', 
            '100'
        );

        Test.stopTest();

        // THEN
        final String TITLE = '%Salesforce Developer%';
        final String LOCATION = '%FL%';

        final List<String> SALARIES = new List<String>{
            '$1,234 per week', 
            '$90.1 - $95.9 per hour', 
            '$90.25k - $100.75k'
        };

        final List<String> SOURCES = new List<String>{
            'nowhere.com', 
            'somewhere.com', 
            'drjobs.ae'
        };

        final List<String> TYPES = new List<String>{
            'Full-time', 
            'Temporary'
        };

        final List<String> COMPANIES = new List<String>{
            'CodeEveryDay', 
            'Salesforce', 
            'Hirekeyz Inc'
        };

        final List<String> JOB_IDS = new List<String>{
            '-1234567890123456789', 
            '-2885668755075351000', 
            '6407669124240903000'
        };

        List<Job__c> retrievedJobs = [
            SELECT Id 
            FROM Job__c 
            WHERE Title__c LIKE :TITLE 
                AND Location__c LIKE :LOCATION 
                AND Salary__c IN :SALARIES 
                AND Source__c IN :SOURCES 
                AND Type__c IN :TYPES 
                AND Company__c IN :COMPANIES 
                AND Id__c IN :JOB_IDS 
            WITH USER_MODE
        ];

        System.assertEquals(3, retrievedJobs.size(), 'Expect 3 retrieved jobs');
    }

    @IsTest
    private static void make_POST_callout_fails() {
        // GIVEN
        joobleJSONCalloutMockGenerator.statusCode = 500;

        Test.setMock(HttpCalloutMock.class, joobleJSONCalloutMockGenerator);

        // WHEN
        Test.startTest();

        try {
            JoobleJSONCallout.makePOSTCallout(
                null, 
                null, 
                null, 
                null, 
                null, 
                null, 
                null
            );

            Test.stopTest();

            // THEN
            Assert.fail('Expect exception');
        } catch (Exception e) {
            System.assertEquals(
                'HTTP request failed | Status Code: 500', 
                e.getMessage(), 
                'Exception message does not match: ' + e.getMessage()
            );
        }

        List<Job__c> retrievedJobs = [
            SELECT Id 
            FROM Job__c 
            WITH USER_MODE
        ];

        System.assertEquals(0, retrievedJobs.size(), 'Expect 0 retrieved job');
    }
}