Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>A custom object to store jobs</description>
    <label>Job</label>
    <nameField>
        <displayFormat>Job-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>A text field to store the job company</description>
    <label>Company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>A text field to store the job Id</description>
    <externalId>true</externalId>
    <label>Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <description>A URL field to store the job link</description>
    <label>Link</label>
    <type>Url</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>A text field to store the job location</description>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>A text field to store the job salary</description>
    <label>Salary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Snippet__c.field-meta.xml
<CustomField>
    <fullName>Snippet__c</fullName>
    <description>A long text area field to store the job snippet</description>
    <label>Snippet</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>A URL field to store the job source</description>
    <label>Source</label>
    <type>Url</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>A text field to store the job title</description>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>A text field to store the job type</description>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Updated__c.field-meta.xml
<CustomField>
    <fullName>Updated__c</fullName>
    <description>A datetime field to store the date and time the job was last updated</description>
    <label>Updated</label>
    <type>DateTime</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/classes/JobController.cls
public with sharing class JobController {
    @AuraEnabled(cacheable=true)
    public static List<Job__c> queryJobs() {
        return [
            SELECT 
                Id, 
                Title__c, 
                Company__c, 
                Location__c, 
                Type__c, 
                Salary__c, 
                Snippet__c, 
                Link__c, 
                Source__c, 
                Updated__c, 
                Id__c 
            FROM Job__c 
            WITH USER_MODE
        ];
    }

    @AuraEnabled
    public static void deleteJobs(List<String> recordIds) {
        if (Schema.sObjectType.Job__c.isDeletable()) {
            delete as user [SELECT Id FROM Job__c WHERE Id IN :recordIds WITH USER_MODE];
        }
    }

    @AuraEnabled
    public static void deleteAllJobs() {
        if (Schema.sObjectType.Job__c.isDeletable()) {
            delete as user [SELECT Id FROM Job__c WITH USER_MODE];
        }
    }
}