Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>A custom object to store jobs</description>
    <label>Job</label>
    <nameField>
        <displayFormat>Job-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>A text field to store the job title</description>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>A custom object to store job applications</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This picklist field will track the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/classes/JobApplicationControllerTest.cls
@IsTest
private with sharing class JobApplicationControllerTest {
    @TestSetup
    private static void setup() {
        TestDataFactory testDataFactory = new TestDataFactory();

        List<Job__c> jobsToInsert = testDataFactory.createJobs_setup_JobApplicationControllerTest();

        if (Schema.sObjectType.Job__c.isCreateable()) {
            insert as user jobsToInsert;
        }

        Job__c jobJrSFDev;
        Job__c jobSFDev;

        for (Job__c jobToInsert : jobsToInsert) {
            if (jobToInsert.Title__c == 'Junior Salesforce Developer') {
                jobJrSFDev = jobToInsert;
            } else if (jobToInsert.Title__c == 'Salesforce Developer') {
                jobSFDev = jobToInsert;
            }
        }

        List<Account> acctsToInsert = testDataFactory.createAccts_setup_JobApplicationControllerTest();

        if (Schema.sObjectType.Account.isCreateable()) {
            insert as user acctsToInsert;
        }

        Id accCodeEveryDayId;
        Id accSalesforceId;

        for (Account accToInsert : acctsToInsert) {
            if (accToInsert.Name == 'CodeEveryDay') {
                accCodeEveryDayId = accToInsert.Id;
            } else if (accToInsert.Name == 'Salesforce') {
                accSalesforceId = accToInsert.Id;
            }
        }

        List<Job_Application__c> jobApplicationsToInsert = testDataFactory.createJobApplications_setup_JobApplicationControllerTest(
            jobJrSFDev, 
            accCodeEveryDayId, 
            jobSFDev, 
            accSalesforceId
        );

        if (Schema.sObjectType.Job_Application__c.isCreateable()) {
            insert as user jobApplicationsToInsert;
        }
    }

    @IsTest
    private static void upsert_job_applications_results_in_four_accounts_and_three_job_applications_with_Saved_status() {
        // GIVEN
        List<Job__c> jobs = [
            SELECT Id 
            FROM Job__c 
            WITH USER_MODE
        ];

        List<String> recordIds = new List<String>();

        for (Job__c job : jobs) {
            recordIds.add(job.Id);
        }

        // WHEN
        Test.startTest();

        JobApplicationController.upsertJobApplications(recordIds);

        Test.stopTest();

        // THEN
        List<Account> retrievedAccts = [
            SELECT Id 
            FROM Account 
            WITH USER_MODE
        ];

        System.assertEquals(4, retrievedAccts.size(), 'Expect 4 accounts');

        final String SAVED = 'Saved';

        List<Job_Application__c> retrievedJobApplications = [
            SELECT Id 
            FROM Job_Application__c 
            WHERE Status__c = :SAVED 
            WITH USER_MODE
        ];

        System.assertEquals(3, retrievedJobApplications.size(), 'Expect 3 job applications with Saved status');
    }
}