Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>A custom object to store jobs</description>
    <label>Job</label>
    <nameField>
        <displayFormat>Job-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>A text field to store the job company</description>
    <label>Company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>A text field to store the job Id</description>
    <externalId>true</externalId>
    <label>Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <description>A URL field to store the job link</description>
    <label>Link</label>
    <type>Url</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>A text field to store the job location</description>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>A text field to store the job salary</description>
    <label>Salary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Snippet__c.field-meta.xml
<CustomField>
    <fullName>Snippet__c</fullName>
    <description>A long text area field to store the job snippet</description>
    <label>Snippet</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>A URL field to store the job source</description>
    <label>Source</label>
    <type>Url</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>A text field to store the job title</description>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>A text field to store the job type</description>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job__c/fields/Updated__c.field-meta.xml
<CustomField>
    <fullName>Updated__c</fullName>
    <description>A datetime field to store the date and time the job was last updated</description>
    <label>Updated</label>
    <type>DateTime</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>A custom object to store job applications</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to an Account that represents the company where the job application is being sent</description>
    <inlineHelpText>Select the company where the job application is being sent</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <description>A long text area to hold detailed information about the job such as responsibilities, qualifications, benefits, etc.</description>
    <inlineHelpText>Information about the job such as responsibilities, qualifications, benefits, etc.</inlineHelpText>
    <label>Job Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>A text field to store the job Id</description>
    <externalId>true</externalId>
    <label>Job Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <description>A picklist field to indicate the job type</description>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>A text field to store the job location</description>
    <inlineHelpText>Job location</inlineHelpText>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <description>A text field to keep track of the specific job title or position being applied
for</description>
    <inlineHelpText>Enter the job position or title being applied for</inlineHelpText>
    <label>Position/Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>A numerical field to capture the expected salary for the job position</description>
    <inlineHelpText>Expected salary for the job position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This picklist field will track the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/objects/Job_Application__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>A URL field to store the web link of the job posting</description>
    <inlineHelpText>Link to Job posting</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

Job-Application-Tracker-main/Job-Application-Tracker-main/force-app/main/default/classes/JobApplicationController.cls
public with sharing class JobApplicationController {
    @AuraEnabled
    public static void upsertJobApplications(List<String> recordIds) {
        List<Job_Application__c> jobApplicationsToUpsert = createJobApplicationsFromJobs(recordIds);

        setStatusToSavedForJobApplicationsWithoutStatus(jobApplicationsToUpsert);

        if (Schema.sObjectType.Job_Application__c.isCreateable() && Schema.sObjectType.Job_Application__c.isUpdateable()) {
            upsert as user jobApplicationsToUpsert Job_Id__c;
        }
    }

    private static List<Job_Application__c> createJobApplicationsFromJobs(List<String> recordIds) {
        List<Job__c> jobs = [
            SELECT 
                Id, 
                Title__c, 
                Location__c, 
                Snippet__c, 
                Salary__c, 
                Source__c, 
                Type__c, 
                Link__c, 
                Company__c, 
                Updated__c, 
                Id__c 
            FROM Job__c 
            WHERE Id IN :recordIds 
            WITH USER_MODE
        ];

        List<Job_Application__c> jobApplications = new List<Job_Application__c>();

        for (Job__c job : jobs) {
            Job_Application__c jobApplication = new Job_Application__c();

            if (!String.isBlank(job.Title__c)) {
                jobApplication.Position_Title__c = job.Title__c;
            }

            if (!String.isBlank(job.Location__c)) {
                jobApplication.Location__c = job.Location__c;
            }

            if (!String.isBlank(job.Snippet__c)) {
                jobApplication.Job_Description__c = job.Snippet__c;
            }

            if (!String.isBlank(job.Salary__c)) {
                try {
                    jobApplication.Salary__c = Decimal.valueOf(job.Salary__c);
                } catch (TypeException e) {
                    final String SALARY_TO_JOB_DESCRIPTION = '\n\nSalary: ' + job.Salary__c;

                    if (String.isBlank(jobApplication.Job_Description__c)) {
                        jobApplication.Job_Description__c = SALARY_TO_JOB_DESCRIPTION.trim();
                    } else {
                        jobApplication.Job_Description__c += SALARY_TO_JOB_DESCRIPTION;
                    }
                }
            }

            if (!String.isBlank(job.Source__c)) {
                final String SOURCE_TO_JOB_DESCRIPTION = '\n\nSource: ' + job.Source__c;

                if (String.isBlank(jobApplication.Job_Description__c)) {
                    jobApplication.Job_Description__c = SOURCE_TO_JOB_DESCRIPTION.trim();
                } else {
                    jobApplication.Job_Description__c += SOURCE_TO_JOB_DESCRIPTION;
                }
            }

            if (
                !String.isBlank(job.Type__c) 
                && (job.Type__c == 'Full-time' || job.Type__c == 'Temporary')
            ) {
                jobApplication.Job_Type__c = job.Type__c;
            }

            if (!String.isBlank(job.Link__c)) {
                jobApplication.URL__c = job.Link__c;
            }

            if (!String.isBlank(job.Company__c)) {
                jobApplication.Company__c = getAccId(job.Company__c);
            }

            if (!String.isBlank(String.valueOf(job.Updated__c))) {
                final String DATE_UPDATED_TO_JOB_DESCRIPTION = '\n\nUpdated: ' + String.valueOf(job.Updated__c);

                if (String.isBlank(jobApplication.Job_Description__c)) {
                    jobApplication.Job_Description__c = DATE_UPDATED_TO_JOB_DESCRIPTION.trim();
                } else {
                    jobApplication.Job_Description__c += DATE_UPDATED_TO_JOB_DESCRIPTION;
                }
            }

            if (!String.isBlank(job.Id__c)) {
                jobApplication.Job_Id__c = job.Id__c;
            }

            jobApplications.add(jobApplication);
        }

        return jobApplications;
    }

    private static String getAccId(String company) {
        String accId;

        if (company != null) {
            List<Account> retrievedAccts = [
                SELECT 
                    Id, 
                    Name 
                FROM Account 
                WHERE Name = :company 
                WITH USER_MODE 
                LIMIT 1
            ];

            if (retrievedAccts.isEmpty()) {
                accId = createAcc(company);
            } else {
                accId = retrievedAccts[0].Id;
            }
        }

        return accId;
    }

    private static Id createAcc(String company) {
        Account accToInsert = new Account(Name = company);

        if (Schema.sObjectType.Account.isCreateable()) {
            insert as user accToInsert;
        }

        return accToInsert.Id;
    }

    private static void setStatusToSavedForJobApplicationsWithoutStatus(List<Job_Application__c> jobApplications) {
        Set<String> jobIds = new Set<String>();

        for (Job_Application__c jobApplication : jobApplications) {
            jobIds.add(jobApplication.Job_Id__c);
        }

        List<Job_Application__c> existingJobApplicationsWithStatus = [
            SELECT Job_Id__c 
            FROM Job_Application__c 
            WHERE Job_Id__c = :jobIds 
                AND Status__c != null 
            WITH USER_MODE
        ];

        Map<String, String> existingJobIdMap = new Map<String, String>();

        for (Job_Application__c existingJobApplicationWithStatus : existingJobApplicationsWithStatus) {
            existingJobIdMap.put(existingJobApplicationWithStatus.Job_Id__c, existingJobApplicationWithStatus.Job_Id__c);
        }

        for (Job_Application__c jobApplication : jobApplications) {
            if (!existingJobIdMap.containsKey(jobApplication.Job_Id__c)) {
                jobApplication.Status__c = 'Saved';
            }
        }
    }
}